function setBans(){
  var banned = {
    "moves":[
      "acupressure",
      "double team",
      "extreme evoboost",
      "fissure",
      "flash",
      "frustration",
      "guillotine",
      "hidden power",
      "hidden power bug",
      "hidden power dark",
      "hidden power dragon",
      "hidden power electric",
      "hidden power fighting",
      "hidden power fire",
      "hidden power flying",
      "hidden power ghost",
      "hidden power grass",
      "hidden power ground",
      "hidden power ice",
      "hidden power poison",
      "hidden power psychic",
      "hidden power rock",
      "hidden power steel",
      "horn drill",
      "kinesis",
      "leaf tornado",
      "mirror shot",
      "minimize",
      "mud bomb",
      "mud-slap",
      "muddy water",
      "night daze",
      "octazooka",
      "pursuit",
      "return",
      "sand attack",
      "secret power",
      "sheer cold",
      "smokescreen"
    ],
    "pokemon":[
      "arceus",
      "darkrai",
      "deoxys",
      "dialga",
      "genesect",
      "giratina",
      "groudon",
      "ho-oh",
      "marshadow",
      "magearna",
      "kyogre",
      "kyurem-w",
      "lugia",
      "lunala",
      "meltan",
      "melmetal",
      "mewtwo",
      "naganadel",
      "necrozma-dawn-wings",
      "necrozma-dusk-mane",
      "necrozma-ultra",
      "paklia",
      "rayquaza",
      "reshiram",
      "shaymin-sky",
      "solgaleo",
      "xerneas",
      "yveltal",
      "zekrom",
      "zeraora",
      "tapu lele",
      "pheromosa",
      "zygarde"
    ],
    "items":[
      "adamant orb",
      "blazikenite",
      "blue orb",
      "bright powder",
      "burn drive",
      "chill drive",
      "douse drive",
      "gengarite",
      "griseous orb",
      "kommonium z",
      "lax incense",
      "lucarionite",
      "lustrous orb",
      "mawilite",
      "metagrossite",
      "salamencite",
      "red orb",
      "shock drive"
    ],
    "abilities":{
      "combos": {
        "greninja": ["battle bond","protean"],
        "blaziken":["speed boost"],
        "landorus":["sheer force"]
      },
      "general":[
        "moody",
        "power construct",
        "sand veil"
      ]
    },
    "misc": {
      "banZ": true,
      "banMegas": true
    }
  }

  return banned;
}
